#!/bin/sh

set -e
set -u

script_name="$(basename "$0")"
script_dir="$(realpath "$(dirname "$0")")"

usage() {
  printf "%s: usage: %s [ build | push ]\n" "$script_name" "$script_name" >&2
}

exit_with_error() {
  printf "%s: error: %s\n" "$script_name" "$1" >&2
  usage
  exit 1
}

recieved_arguments="$#"
expected_arguments="1"

if [ "${recieved_arguments}" != "${expected_arguments}" ]; then
  exit_with_error "invalid number of arguments, expected \"${expected_arguments}\", recieved \"${recieved_arguments}\""
fi

docker_build() {
  if ! "$script_dir/docker-build"; then
    exit_with_error "failed to run $script_dir/docker-build"
  fi
}

docker_push() {
  if ! "$script_dir/docker-push"; then
    exit_with_error "failed to run $script_dir/docker-push"
  fi
}

if [ "$1" != "build" ] && [ "$1" != "push" ]; then
  exit_with_error "invalid argument, expected [ build | push ], recieved \"$1\""
fi

if [ "$1" = "build" ]; then
  docker_build
elif [ "$1" = "push" ]; then
  docker_push
fi
