#!/bin/sh

set -e
set -u

script_name="$(basename "$0")"
script_dir="$(realpath "$(dirname "$0")")"

usage() {
  printf "%s: usage: %s ROOT_DIRECTORY\n" "$script_name" "$script_name" >&2
}

exit_with_error() {
  printf "%s: error: %s\n" "$script_name" "$1" >&2
  usage
  exit 1
}

recieved_arguments="$#"
expected_arguments="1"

if [ "${recieved_arguments}" != "${expected_arguments}" ]; then
  exit_with_error "invalid number of arguments, expected \"${expected_arguments}\", recieved \"${recieved_arguments}\""
fi

set +e

DOCKER_IMAGE="$(printenv DOCKER_IMAGE)"

set -e

if [ -n "${DOCKER_IMAGE}" ]; then
  printf "%s\n" "${DOCKER_IMAGE}"
  return 0
fi

extract_variable() {
  if [ ! -r "$2" ]; then
    exit_with_error "failed to read \"$2\" file"
  fi

  grep "^${1}=" "${2}" | sed -E "s/^${1}=(.*)$/\1/"
}

root_dir="$(realpath "$script_dir/..")" &&
  extract_variable "DOCKER_IMAGE" "$root_dir/.env"
